37. Практика , ч4. Используем объекты
OleksandrCherna/udemy_java_script_react pull request #25
Opened 2023-11-30 16:51 UTC by OleksandrCherna

2023-11-30 21:28 UTC, valeragh requested changes

2023-11-30 21:28 UTC, valeragh commented on oop_practice/index.html
> +</html>
Add please empty line

2023-11-30 21:28 UTC, valeragh commented on oop_practice/script.js
> +};
Where is your console.logs tests?

2023-12-01 15:30 UTC, OleksandrCherna commented on oop_practice/script.js
> +};
работает только в браузере через консоль

2023-12-01 20:40 UTC, valeragh approved these changes

2023-12-03 18:47 UTC, merged