Coding Exercise 14: (*) Продвинутая задача на работу с объектами и ма…
OleksandrCherna/udemy_java_script_react pull request #27
Opened 2023-12-03 18:48 UTC by OleksandrCherna

…ссивами

2023-12-03 20:15 UTC, valeragh requested changes

2023-12-03 20:15 UTC, valeragh commented on coding_exercise_14/script.js
> +}if (i >= 0 && i <= 2) { a.push(item); }
It is error, put this in line 71

2023-12-25 14:24 UTC, OleksandrCherna commented on coding_exercise_14/script.js
> +}if (i >= 0 && i <= 2) { a.push(item); }
fixed

2023-12-25 15:55 UTC, valeragh approved these changes

2023-12-26 18:11 UTC, merged